environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

test_script:
  - gulp --appveyor=true continous-integration

build: off

artifacts:
  - path: 'out\build\*.js'
    name: it-depends

deploy:
  release: 'it-depends $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  prerelease: true
  auth_token:
    secure: iIQYZTIjnJwRMu4NGFO9iDWVxiULK/6RfSWY6R9Z8W7daJPdGQGMBqblEcpYa9xZ
  artifact: it-depends
  on:
    branch: master
    appveyor_repo_tag: true