environment:
  npmrc_token:
    secure: 827ODotTjWRaqvdFThFhYxnq+4W6qz7RtrtxGYuPPN0=

  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"

install:
  - ps: >-
      if($env:APPVEYOR_REPO_TAG_NAME -and $env:nodejs_version -eq '0.12') {
        ./build/publish/decrypt-npmrc.ps1
      }
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

test_script:
  - gulp --appveyor=true continous-integration

build: off

artifacts:
  - path: 'out\build\*.js'
    name: it-depends

on_success:
  - ps: >-
      if($env:APPVEYOR_REPO_TAG_NAME -and $env:nodejs_version -eq '0.12') {
         ./build/publish/publish-npm.ps1
      }
deploy:
  tag: '$(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure: iIQYZTIjnJwRMu4NGFO9iDWVxiULK/6RfSWY6R9Z8W7daJPdGQGMBqblEcpYa9xZ
  artifact: it-depends
  on:
    branch: master
    appveyor_repo_tag: true
    nodejs_version: "0.12"

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json